WebPageLink = "https://www.flipkart.com"
WebPageLink2 = "http://demo.guru99.com/V1/index.php"
WebPageLink3 = "https://gsuite.google.com/intl/en_in/"
GitHubLink = "https://github.com"
Search = "//*[@id=\"lst-ib\"]"
Title_Text = "//*[@id=\"hplogo\"]"
signin = "/html/body/div[1]/header/div/div[2]/div/span/div/a[1]"
Enter_user = "//*[@id=\"login_field\"]"
Enter_pass = "//*[@id=\"password\"]"
Search_1 = "/html/body/div[1]/header/div/div[2]/div[1]/div/div/div/form/label/input[1]"
Upload_files = "/Varun777123/NewTest/upload/master"
Choose_file = "/html/body/div[4]/div/div/div[2]/div[1]/div[2]/form[2]/div/p/input"
file_path = "D:\\Training\\Training\\test1234.txt"
search_button = "//*[contains(@name,'btnK')]"
gmail_link = "//*[contains(@href, 'https://mail.google.com')]"
gmail_link = "/html/body/div/div[3]/div[1]/div/div/div/div[1]/div[1]/a"
mens_section = "/html/body/div[2]/header/div[2]/div/nav/ul/li[1]/a"
mens_section = "//*[contains(@href, '/mens-clothing')]"
Cart_xpath = "//span[text() = 'Cart']"
Empty_cart_xpath = "//*[text() = 'Your Shopping Cart is empty']"
submit_carter = "//*[@type='submit' and @value='Sign in']"
Resources_xpath = "//a[contains(@class, 'navigation--item navigation') and text() = 'Resources']"
Training_xpath = "//a[contains(@class, 'navigation--item') and text() = 'Training & Certification']"
security_xpath = "//a[@href = './security/' and @class = 'navigation--item']"
close_flipkart_modal = "//button[contains(@class, '_2AkmmA _29YdH8')]"
flipkart_login_xpath = "//a[contains(@href, '/account/login')]"
flipkart_login_email = "//input[@type = 'text' and @class = '_2zrpKA']"
flipkart_login_pass = "//input[@type = 'password' and @class = '_2zrpKA _3v41xv']"
flipkart_login_button = "//button[@type = 'submit' and @class = '_2AkmmA _1LctnI _7UHT_c']"
